/*
 * Copyright © 2023 Aptimyz Retail LTD. All Rights Reserved.
 *
 * This software is the proprietary information of Aptimyz Retail LTD.
 * Use, reproduction, disclosure, or distribution of this software and related
 * documentation without an express written agreement from Aptimyz Retail LTD is strictly prohibited.
 *
 * This software may incorporate open-source software, the use of which is
 * governed by their respective licenses as designated in the included
 * OSS-licenses documentation generated by the oss-licenses-plugin.
 *
 * This software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
 * except as required by applicable law.
 *
 * The software is available on Clover Market, soon to be available on Apple App Store and Google Play.
 */

package com.xeladevmobile.medicalassistant.core.network.model

import com.xeladevmobile.medicalassistant.core.model.data.UserType
import kotlinx.serialization.Serializable
import java.util.*

@Serializable
data class NetworkUser(
    val name: String,
    val sex: String,
    val bornDate: String,
    val address: String,
    val userType: UserType,

    // Patient
    val patientId: String,
    val problemDescription: String,
    val treatmentDate: String,

    // Doctor
    val doctorId: String,
    val specialty: String,
    val graduationDate: String,
    val experience: String,
    val occupation: String,
)

val networkUserForTestWithPatient = NetworkUser(
    name = "Alex Rivas Martinez",
    sex = "Masculino",
    bornDate = "1999-03-09",
    address = "Calle 1 # 2-3",
    userType = UserType.PATIENT,
    problemDescription = "Paciente con problemas de cognitividad y memoria",
    treatmentDate = "2021-09-09",
    specialty = "",
    graduationDate = "",
    experience = "",
    occupation = "",
    patientId = UUID.randomUUID().toString(),
    doctorId = "",
)

val networkUserForTestWithDoctor = NetworkUser(
    name = "José Feliciano de la Paz",
    sex = "Masculino",
    bornDate = "1995-05-09",
    address = "Calle 15 #23-34",
    userType = UserType.DOCTOR,
    problemDescription = "",
    treatmentDate = "",
    specialty = "Neurología",
    graduationDate = "2020-09-09",
    experience = "2 años",
    occupation = "Neurólogo",
    patientId = "",
    doctorId = UUID.randomUUID().toString(),
)
