/*
 * Copyright © 2023 Aptimyz Retail LTD. All Rights Reserved.
 *
 * This software is the proprietary information of Aptimyz Retail LTD.
 * Use, reproduction, disclosure, or distribution of this software and related
 * documentation without an express written agreement from Aptimyz Retail LTD is strictly prohibited.
 *
 * This software may incorporate open-source software, the use of which is
 * governed by their respective licenses as designated in the included
 * OSS-licenses documentation generated by the oss-licenses-plugin.
 *
 * This software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
 * except as required by applicable law.
 *
 * The software is available on Clover Market, soon to be available on Apple App Store and Google Play.
 */

package com.xeladevmobile.medicalassistant.feature.login

import com.xeladevmobile.medicalassistant.core.network.model.NetworkUser

sealed interface LoginUiState {
    object Initial : LoginUiState
    object Loading : LoginUiState
    data class Success(val networkUserData: NetworkUser) : LoginUiState
    data class Error(val message: String) : LoginUiState
}
